### PR TITLE
Example python script

### PR DESCRIPTION
**Pull request by jburel**
* Review the setup indicating how to use Docker image built using ``repo2docker``
* Add python example that can be run from terminal
To test:
* run repo2docker locally or go to mybinder
* When the image is ready, copy the URL in browser (instructions have been added to setup)
* Click New > Terminal
* Activate the conda env named ``kernel``
* go to scripts
* run ``python idr0002_save.py``.
The various steps of the script are described in gettingstarted.
The script folder also contains solution to exercises listed at the end of the gettingstarted page

cc @pwalczysko

### CODE REVIEW

**Comment by will-moore** [comment]
Just for the record, this worked for @pwalczysko but failed for me with

```
conda env update -n cellprofiler --file binder/environment.yml
...
...
In file included from /Users/wmoore/opt/miniconda3/envs/cellprofiler/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
    /Users/wmoore/opt/miniconda3/envs/cellprofiler/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    centrosome/_lapjv.cpp:860:14: fatal error: 'complex' file not found
        #include <complex>
                 ^~~~~~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/wmoore/opt/miniconda3/envs/cellprofiler/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b5/_dnzdy750_s53w_21t6lvf61cn9pqx/T/pip-install-O4z5qN/centrosome/setup.py'"'"'; __file__='"'"'/private/var/folders/b5/_dnzdy750_s53w_21t6lvf61cn9pqx/T/pip-install-O4z5qN/centrosome/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b5/_dnzdy750_s53w_21t6lvf61cn9pqx/T/pip-record-OZiLbP/install-record.txt --single-version-externally-managed --compile --install-headers /Users/wmoore/opt/miniconda3/envs/cellprofiler/include/python2.7/centrosome Check the logs for full command output.


CondaEnvException: Pip failed
```

**Comment by jburel** [comment]
The problem occurs during the installation of cp, it tries to rebuild one of the components of CP.
Hopefully the problem will disappear in CP 4 (end of April)
the best strategy is to
*  run locally ``repo2docker .``
* use the ``kernel`` conda env created during that phase as described in the ``setup`` file.

**Comment by jburel** [comment]
@will-moore This thread might help https://github.com/skggm/skggm/issues/117
basically upgrade Xcode

**Comment by will-moore** [comment]
Unfortunately I get the same error after installing latest XCode for my Mac version. XCode 11.3.1 for Mac 10.14.6...

```
(base) LS30778:cellprofiler wmoore$ which gcc
/usr/bin/gcc
(base) LS30778:cellprofiler wmoore$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by pwalczysko** [comment]
For me the workflow of CP running locally and connecting to OMERO using python code works.

Mac OS High Sierra version 10.13.6

I do not know if I even have XCode installed. Cannot see it in my Apps folder.
Compare my output below with @will-moore 's above

```
(cellprofiler) pwalczysko@ls31618~$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jburel** [comment]
I think the best for @will-moore will be to use the env created in the docker container.
instructions are added in the setup file

**Comment by jburel** [comment]
Travis failure fixed in https://github.com/ome/omero-guide-cellprofiler/pull/8

**Comment by pwalczysko** [comment]
After using ``repo2docker`` install, then going to the terminal in Jupyter as instructed

```
(kernel) pwalczysko@4722499de0fd:~$ python scripts/idr0002_save
idr0002_save.py            idr0002_save_solution1.py  idr0002_save_solution2.py  idr0002_save_solution3.py
(kernel) pwalczysko@4722499de0fd:~$ python scripts/idr0002_save.py
/srv/conda/envs/kernel/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Host [wss://workshop.openmicroscopy.org/omero-ws]:
Username [trainer-1]:
Password:
Plate ID [102]:
Traceback (most recent call last):
  File "scripts/idr0002_save.py", line 156, in <module>
    main()
  File "scripts/idr0002_save.py", line 143, in main
    pipeline = load_pipeline(pipeline_path)
  File "scripts/idr0002_save.py", line 63, in load_pipeline
    pipeline.load(pipeline_path)
  File "/srv/conda/envs/kernel/lib/python2.7/site-packages/cellprofiler/pipeline.py", line 792, in load
    raise IOError("Could not find file, " + fd_or_filename)
IOError: Could not find file, ../notebooks/pipelines/ExamplePercentPositive.cppipe
!! 04/28/20 12:31:54.247 error: communicator not destroyed during global destruction.(kernel) pwalczysko@4722499de0fd:~$
```

Note: Got the same error for the first example script.

**Comment by pwalczysko** [comment]
Mybinder from this branch (sample) failed with

```
inja2-2.11.1        | 104 KB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base conda


Pip subprocess error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-LgxiBD/centrosome/
You are using pip version 10.0.1, however version 20.1b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


CondaEnvException: Pip failed

Ran pip subprocess with arguments:
['/srv/conda/envs/kernel/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/jovyan/binder/condaenv.dfs0uwnn.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/CellProfiler/CellProfiler.git@v3.1.9 (from -r /home/jovyan/binder/condaenv.dfs0uwnn.requirements.txt (line 3))
  Cloning https://github.com/CellProfiler/CellProfiler.git (to revision v3.1.9) to /tmp/pip-req-build-X3Qygv
```

**Comment by jburel** [comment]
This branch will not work, due to the bug fixed in the other PR
The code changes have already been reviewed. Only the last commit (text) needs to be checked

**Comment by jburel** [comment]
This could be due to your connection
something might have not worked during the cloning phase

**Comment by pwalczysko** [comment]
The text in the last commit reads and builds okay.

**Comment by pwalczysko** [comment]
ready to merge fmpov

**Comment by pwalczysko** [comment]
great, travis is green here too

**Comment by jburel** [comment]
It is now green after merging #8

**Pull request merged**
