### PR TITLE
Update hcs

### PR DESCRIPTION
**Pull request by jburel**
This PR 
 * caps the version of the zarr dependency. It did not work anymore
 * loads the data using the new HCS zarr structure

### CODE REVIEW

**Review by manics — APPROVED** [review]
LGTM, though travis is taking forever.....

**Comment by jburel** [comment]
https://github.com/jburel/omero-guide-cellprofiler/actions/runs/334243765 is green

**Comment by sbesson** [comment]
> https://github.com/jburel/omero-guide-cellprofiler/actions/runs/334243765 is green

Looks good. Two questions:
- are we acting the switch from Travis CI to GitHub actions for this repo i.e. is it worth removing .travis.yml as part of this PR?
- probably outside the scope of this PR, it looks like this could be split into two generic re-usable GitHub workflows: 1- install and run Sphinx and 2- install and run repo2docker. Thoughts ?

**Comment by jburel** [comment]
For travis: I am for removing it from this repo. So happy to do that in this PR

I was thinking to actually move the "sphinx" part to the template guide and split the 2 now that we have it in place
Most repo will follow exactly the same pattern so it makes sense to have 2 generic workflows

**Review by sbesson — APPROVED** [review]
The CI infrastructure changes make sense to me and can be refined in follow-up PRs. Leaving @manics to give the last commits a final review.

**Review by manics — APPROVED** [review]

**Pull request merged**
