### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by jburel**
Update the instructions following feedback from workshop
cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
Did you want to list this on Standup ?

**Comment by pwalczysko** [comment]
Did you want to list this at Standup ?

**Comment by dominikl** [comment]
Looks good. Notebook works on mybinder. Not sure about the repo2docker thing, but should definitely merge the notebook.

**Comment by pwalczysko** [comment]
> Not sure about the repo2docker thing, but should definitely merge the notebook.

@dominikl but the repo2docker built locally works just fine for this repo - the problem https://github.com/ome/omero-guide-r/pull/2#issuecomment-582077572 you are mentioning is specific for R repo only https://github.com/ome/omero-guide-r/pull/2 
The local build of repo2docker works fine here and also in the python repo https://github.com/ome/omero-guide-python/pull/2#issuecomment-582495192

**Pull request merged**
