### PR TITLE
Cp4

### PR DESCRIPTION
**Pull request by jburel**
This PR upgrades CellProfiler to version 4 which has Python 3 support
Update so we can engage on zarr
cc @pwalczysko

To test:
* Check that the notebooks still work
* Check the scripts

Edit: Bump to 4.1.3 where the problem described below has been fixed
~~There was a problem with the version of numpy used by cp
see https://github.com/CellProfiler/CellProfiler/issues/4353~~

### CODE REVIEW

**Comment by pwalczysko** [comment]
In the ``idr_0002_save`` notebook, following error (built on MyBinder using the badge in the comment above)


```
HOST = 'wss://workshop.openmicroscopy.org/omero-ws'

conn = BlitzGateway(raw_input("Username: "),

                    getpass("OMERO Password: "),

                    host=HOST, secure=True)

print(conn.connect())

conn.c.enableKeepAlive(60)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-36ea3b147b88> in <module>
      1 HOST = 'wss://workshop.openmicroscopy.org/omero-ws'
----> 2 conn = BlitzGateway(raw_input("Username: "),
      3                     getpass("OMERO Password: "),
      4                     host=HOST, secure=True)
      5 print(conn.connect())

NameError: name 'raw_input' is not defined

```

the notebook ``statistics_fruit_fly`` has analogical error as the one above.

**Comment by pwalczysko** [comment]
```
(notebook) jovyan@jupyter-jburel-2domero-2dguide-2dcellprofiler-2d31sw5el8:~/scripts$ python idr0002_idr_zarr.py
Traceback (most recent call last):
  File "idr0002_idr_zarr.py", line 150, in main
    plate_id = raw_input("Plate ID [422]: ") or '422'
NameError: name 'raw_input' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "idr0002_idr_zarr.py", line 169, in <module>
    main()
  File "idr0002_idr_zarr.py", line 164, in main
    disconnect(conn)
UnboundLocalError: local variable 'conn' referenced before assignment
(notebook) jovyan@jupyter-jburel-2domero-2dguide-2dcellprofiler-2d31sw5el8:~/scripts$
```

Analogically to the notebooks, all the scripts are failing with the ``raw_input not defined`` error. This is different from the notebooks in the sense that not all notebooks fail, (but script do all fail, with the output as above or a simpler output similar to the error output reported for the idr0002_save notebook in previous comment

**Comment by jburel** [comment]
thanks for spotting it ``raw_input`` is a python 2 method

**Comment by jburel** [comment]
@pwalczysko sorry about that. This is fixed now

**Comment by pwalczysko** [comment]
> @pwalczysko sorry about that. This is fixed now

Np. the ``...save`` notebook works now fine. I will test the other notebooks and scripts tomorrow, could you please relist ?

**Comment by pwalczysko** [comment]
The ``..._save`` notebook works as indicated yesterday. But there is an output on the cell which produces the blue histogram plots. Just before the histograms are displayed, a confusing output is made, which neccessitates scrolling down to see the graphs. This is not the case in the analogical idr notebook, where no such output appears.
Not a blocker, but would be nicer without those lines.

```
array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7fd38b0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7f40ee0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7f666a0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7f10b50>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7f3dfd0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7ef7490>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7e842e0>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7eb17f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7e07fa0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7e34760>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7de0be0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7d98df0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7d45550>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa1a7d719d0>],
....
```

**Comment by pwalczysko** [comment]
A bug in the notebook ``statistics...`` which works on Dataset (as opposed to a plate). The cell which saves results back to OMERO seems to have a syntax error. Expand the details below to see the errror.

<details>

```
import glob

​

for file_to_upload in glob.glob(new_output_directory + '/*.csv'):

​

    if file_to_upload.endswith('Nuclei.csv'):

        Nuclei.to_csv(file_to_upload)

    elif file_to_upload.endswith('Cells.csv'):

        Cells.to_csv(file_to_upload)

    elif file_to_upload.endswith('Cytoplasm.csv'):

        Cytoplasm.to_csv(file_to_upload)

    elif file_to_upload.endswith('Image.csv'):

        Image.to_csv(file_to_upload)

​

    # create the original file and file annotation (uploads the file etc.)

    namespace = "training.meeting.demo"

    print("\nCreating an OriginalFile and FileAnnotation")

    file_ann = conn.createFileAnnfromLocalFile(file_to_upload, mimetype="text/plain", ns=namespace, desc=None)

    print("Attaching FileAnnotation to Dataset: ", "File ID:", file_ann.getId(), \)

        ",", file_ann.getFile().getName(), "Size:", file_ann.getFile().getSize()

    dataset.linkAnnotation(file_ann)

  File "<ipython-input-13-4ea904e52ec4>", line 18
    print("Attaching FileAnnotation to Dataset: ", "File ID:", file_ann.getId(), \)
                                                                                   ^
SyntaxError: unexpected character after line continuation character
```

</details>

**Comment by pwalczysko** [comment]
All other notebooks work fine. All scripts work fine as run from the terminal in the notebook conda env from the folder ``scripts``. 

In summary
1 [Bug](https://github.com/ome/omero-guide-cellprofiler/pull/16#issuecomment-779777492) and 1 [RFE](https://github.com/ome/omero-guide-cellprofiler/pull/16#issuecomment-779771552)

**Comment by jburel** [comment]
@pwalczysko Bug and RFE should now be fixed

**Comment by pwalczysko** [comment]
Thank you. Works as expected. Ready to merge fmpov

**Comment by jburel** [comment]
@pwalczysko  I have bumped to 4.1.3, it fixes the problem I noticed when building the docker image.
I have retested the notebooks and it still works. You may want to re-run them before we merge.
as mentioned yesterday, we will merge after this week training so no rush

**Comment by pwalczysko** [comment]
This is now in the idr0002.ipyb notebook, see below. Was reported as RFE above and fixed, but now it is back, and in a different notebook.


```
array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7fa3a66fd430>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa3a6712af0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa3a673afd0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa3a66f0490>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa3a669a970>,
```

**Comment by jburel** [comment]
Ok, I don't know why it did not show up the first time in the notebook.
I will clean that up

**Comment by pwalczysko** [comment]
> Ok, I don't know why it did not show up the first time in the notebook.
> I will clean that up

Yes, maybe I missed it back then. Finding now that the ``idr0002_zarr`` notebook has the same problem as well.

**Comment by pwalczysko** [comment]
Sorry, I have discovered one more bug. But, this bug was there before this PR as well. If the csv outputs of the ``statistics_fruit_fly`` notebook are studied in Excel, then you can see that they have the column headers shifted one to the right with respect to the content in the cells below. See screenshot.

Screenshot 2021-02-24 at 12 26 22

**Comment by pwalczysko** [comment]
In summary, 2 issues : the cleanup of the [graph output]( https://github.com/ome/omero-guide-cellprofiler/pull/16#issuecomment-785024384) in 2 notebooks and the [shift of column headers](https://github.com/ome/omero-guide-cellprofiler/pull/16#issuecomment-785041671).

the shift of column headers was a pre-existing problem, so imho this can be fixed in a separate PR if need be.

**Comment by jburel** [comment]
@pwalczysko plotting issue should be now fixed.

**Comment by jburel** [comment]
@pwalczysko I don't think the headers are shifted. The term ``ImageNumber`` is used by default by CP since it works on given 2D "image" on disk by default. I do not really want to chance that

**Comment by pwalczysko** [comment]
> @pwalczysko I don't think the headers are shifted. The term `ImageNumber` is used by default by CP since it works on given 2D "image" on disk by default. I do not really want to chance that

But the headers are shifted.  I have two more indications for this. The last header in the same CSV is heading an empty column. Also in the screenshot, the ImageNumber is fine, but it is above a column which should be headed with "Image Name". And, the "Image Name" header is next to the right of it, heading another column, which contains something else (but not image names, because these are already in column B). And so on. I have another CSV (the notebook produces 4 CSVs) whcih has exactly the same shift - it is not "ImageNumber" specific by any means.

**Comment by pwalczysko** [comment]
Further on the shift of the headers - I think I know why it is there.  Please see attached CSV. This is from https://workshop.openmicroscopy.org/webclient/?show=dataset-1996 - I simply downloaded one of the CSVs attached to that Dataset. You can see in the CSV that it starts with comma, which seems wrong and it might cause the first empty column header, which then in turn causes the shift of the headers to the right.
(will pass the CSV by other means, as cannot upload it here)

Edit - uh, sorry, the last column actually  is not heading the empty cells, so the shift is not there....  no idea then what the headers are saying though then...  I mean the case in the screenshot https://github.com/ome/omero-guide-cellprofiler/pull/16#issuecomment-785041671 seems to be a mislabeled second column, as the column is not heading any number, instead, it is heading something which looks like image name. But the next header to the right is not Image Name, but something else..... 

Edit 2: the column Object Number in the Nuclei.csv matches the content ... So I guess you are right, there is no shift, although it will be disconcerting for the users to not have a first column without a header. Probably best to leave as is.

**Comment by pwalczysko** [comment]
I am erroring already the second time on MyBinder with

```
Error running configure
  ERROR: failed building wxWidgets
  Traceback (most recent call last):
    File "build.py", line 1471, in cmd_build_wx
      wxbuild.main(wxDir(), build_options)
    File "/tmp/pip-install-exntla52/wxpython_469a0d51c1ba4ea981d99b4e7346b81d/buildtools/build_wxwidgets.py", line 372, in main
      exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
    File "/tmp/pip-install-exntla52/wxpython_469a0d51c1ba4ea981d99b4e7346b81d/buildtools/build_wxwidgets.py", line 85, in exitIfError
      raise builder.BuildError(msg)
  buildtools.builder.BuildError: Error running configure
  Finished command: build_wx (0m20.320s)
  Finished command: build (0m20.320s)
  Command '"/srv/conda/envs/notebook/bin/python" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxPython
    ERROR: Command errored out with exit status 1:
     command: /srv/conda/envs/notebook/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-exntla52/wxpython_469a0d51c1ba4ea981d99b4e7346b81d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-exntla52/wxpython_469a0d51c1ba4ea981d99b4e7346b81d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uxrb4skc/install-record.txt --single-version-externally-managed --compile --install-headers /srv/conda/envs/notebook/include/python3.8/wxPython
         cwd: /tmp/pip-install-exntla52/wxpython_469a0d51c1ba4ea981d99b4e7346b81d/
    Complete output (137 lines):
    running install
    running build
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    "/srv/conda/envs/notebook/bin/python" -u build.py build
    Will build using: "/srv/conda/envs/notebook/bin/python"
    3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:21:18)
    [GCC 9.3.0]
    Python's architecture is 64bit
    cfg.VERSION: 4.1.0
```

**Comment by jburel** [comment]
A new version of ``wxPython (4.1.1 )`` was pushed yesterday and in cp the version has been pinned to ``4.1.0`` in cp ``4.1.3`` it was in ``4.0.7`` set to ``>=4.1.0``.

**Comment by jburel** [comment]
@pwalczysko It should now built on mybinder. See
Screenshot 2021-02-26 at 13 54 26

**Comment by pwalczysko** [comment]
All notebooks and scripts work as expected now.

Ready to merge fmpov

**Pull request merged**
