### PR TITLE
update cellprofiler version

### PR DESCRIPTION
**Pull request by jburel**
Update cellprofiler to 4.2.1
Check that the notebooks still work
cc @pwalczysko

### CODE REVIEW

**Comment by jburel** [comment]
Ahead of the upcoming workshops, this should be reviewed cc @pwalczysko

**Comment by pwalczysko** [comment]
Keeps failing on MyBinder with

``Failed to connect to event stream``

**Comment by pwalczysko** [comment]
``repo2docker`` build worked. When single notebooks were run, the 

``idr0002_zarr.ipynb`` notebook fails on the cell ``Run Cell Profiler Pipeline on the plate`` with floowing error (click to expand)

<details>

```
Well: 1/5 row: 4 column: 10
E
idr/share/community-call-2020-10-29/idr0002-heriche-condensation/plate1_1_013/422.zarr/Run 422/E/11/Field_1/0

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/storage.py in __getitem__(self, key)
   2216             with self._mutex:
-> 2217                 value = self._values_cache[key]
   2218                 # cache hit if no KeyError is raised

KeyError: '.zarray'

During handling of the above exception, another exception occurred:

EndpointConnectionError                   Traceback (most recent call last)
<timed exec> in <module>

<ipython-input-6-03fec13bfe35> in load_dask_array_from_s3(run, column, name, field, resolution)
     17     cached_store = zarr.LRUStoreCache(store, max_size=(cache_size_mb * 2**20))
     18     # data.shape is (t, c, z, y, x) by convention
---> 19     return da.from_zarr(cached_store)

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask/array/core.py in from_zarr(url, component, storage_options, chunks, name, inline_array, **kwargs)
   3385     else:
   3386         mapper = url
-> 3387         z = zarr.Array(mapper, read_only=True, path=component, **kwargs)
   3388     chunks = chunks if chunks is not None else z.chunks
   3389     if name is None:

/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/core.py in __init__(self, store, path, read_only, chunk_store, synchronizer, cache_metadata, cache_attrs, partial_decompress, write_empty_chunks)
    178 
    179         # initialize metadata
--> 180         self._load_metadata()
    181 
    182         # initialize attributes

/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/core.py in _load_metadata(self)
    195         """(Re)load metadata from store."""
    196         if self._synchronizer is None:
--> 197             self._load_metadata_nosync()
    198         else:
    199             mkey = self._key_prefix + array_meta_key

/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/core.py in _load_metadata_nosync(self)
    204         try:
    205             mkey = self._key_prefix + array_meta_key
--> 206             meta_bytes = self._store[mkey]
    207         except KeyError:
    208             raise ArrayNotFoundError(self._path)

/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/storage.py in __getitem__(self, key)
   2223         except KeyError:
   2224             # cache miss, retrieve value from the store
-> 2225             value = self._store[key]
   2226             with self._mutex:
   2227                 self.misses += 1

/srv/conda/envs/notebook/lib/python3.8/site-packages/zarr/storage.py in __getitem__(self, key)
    543 
    544     def __getitem__(self, key):
--> 545         return self._mutable_mapping[key]
    546 
    547     def __setitem__(self, key, value):

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
    133         k = self._key_to_str(key)
    134         try:
--> 135             result = self.fs.cat(k)
    136         except self.missing_exceptions:
    137             if default is not None:

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
     83     def wrapper(*args, **kwargs):
     84         self = obj or args[0]
---> 85         return sync(self.loop, func, *args, **kwargs)
     86 
     87     return wrapper

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py in sync(loop, func, timeout, *args, **kwargs)
     63         raise FSTimeoutError from return_result
     64     elif isinstance(return_result, BaseException):
---> 65         raise return_result
     66     else:
     67         return return_result

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py in _runner(event, coro, result, timeout)
     23         coro = asyncio.wait_for(coro, timeout=timeout)
     24     try:
---> 25         result[0] = await coro
     26     except Exception as ex:
     27         result[0] = ex

/srv/conda/envs/notebook/lib/python3.8/site-packages/fsspec/asyn.py in _cat(self, path, recursive, on_error, batch_size, **kwargs)
    395             ex = next(filter(is_exception, out), False)
    396             if ex:
--> 397                 raise ex
    398         if (
    399             len(paths) > 1

/srv/conda/envs/notebook/lib/python3.8/asyncio/tasks.py in wait_for(fut, timeout, loop)
    453 
    454     if timeout is None:
--> 455         return await fut
    456 
    457     if timeout <= 0:

/srv/conda/envs/notebook/lib/python3.8/site-packages/s3fs/core.py in _cat_file(self, path, version_id, start, end)
    906         else:
    907             head = {}
--> 908         resp = await self._call_s3(
    909             "get_object",
    910             Bucket=bucket,

/srv/conda/envs/notebook/lib/python3.8/site-packages/s3fs/core.py in _call_s3(self, method, *akwarglist, **kwargs)
    300                 err = e
    301         err = translate_boto_error(err)
--> 302         raise err
    303 
    304     call_s3 = sync_wrapper(_call_s3)

/srv/conda/envs/notebook/lib/python3.8/site-packages/s3fs/core.py in _call_s3(self, method, *akwarglist, **kwargs)
    280         for i in range(self.retries):
    281             try:
--> 282                 out = await method(**additional_kwargs)
    283                 return out
    284             except S3_RETRYABLE_ERRORS as e:

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/client.py in _make_api_call(self, operation_name, api_params)
    212         else:
    213             apply_request_checksum(request_dict)
--> 214             http, parsed_response = await self._make_request(
    215                 operation_model, request_dict, request_context)
    216 

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/client.py in _make_request(self, operation_model, request_dict, request_context)
    232     async def _make_request(self, operation_model, request_dict, request_context):
    233         try:
--> 234             return await self._endpoint.make_request(operation_model, request_dict)
    235         except Exception as e:
    236             await self.meta.events.emit(

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/endpoint.py in _send_request(self, request_dict, operation_model)
     81         success_response, exception = await self._get_response(
     82             request, operation_model, context)
---> 83         while await self._needs_retry(attempts, operation_model,
     84                                       request_dict, success_response,
     85                                       exception):

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/endpoint.py in _needs_retry(self, attempts, operation_model, request_dict, response, caught_exception)
    219             service_id,
    220             operation_model.name)
--> 221         responses = await self._event_emitter.emit(
    222             event_name, response=response, endpoint=self,
    223             operation=operation_model, attempts=attempts,

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/hooks.py in _emit(self, event_name, kwargs, stop_on_response)
     27                 response = await handler(**kwargs)
     28             else:
---> 29                 response = handler(**kwargs)
     30 
     31             responses.append((handler, response))

/srv/conda/envs/notebook/lib/python3.8/site-packages/botocore/retryhandler.py in __call__(self, attempts, response, caught_exception, **kwargs)
    192             checker_kwargs.update({'retries_context': retries_context})
    193 
--> 194         if self._checker(**checker_kwargs):
    195             result = self._action(attempts=attempts)
    196             logger.debug("Retry needed, action of: %s", result)

/srv/conda/envs/notebook/lib/python3.8/site-packages/botocore/retryhandler.py in __call__(self, attempt_number, response, caught_exception, retries_context)
    265             )
    266 
--> 267         should_retry = self._should_retry(attempt_number, response,
    268                                           caught_exception)
    269         if should_retry:

/srv/conda/envs/notebook/lib/python3.8/site-packages/botocore/retryhandler.py in _should_retry(self, attempt_number, response, caught_exception)
    292             # If we've exceeded the max attempts we just let the exception
    293             # propogate if one has occurred.
--> 294             return self._checker(attempt_number, response, caught_exception)
    295 
    296 

/srv/conda/envs/notebook/lib/python3.8/site-packages/botocore/retryhandler.py in __call__(self, attempt_number, response, caught_exception)
    331     def __call__(self, attempt_number, response, caught_exception):
    332         for checker in self._checkers:
--> 333             checker_response = checker(attempt_number, response,
    334                                        caught_exception)
    335             if checker_response:

/srv/conda/envs/notebook/lib/python3.8/site-packages/botocore/retryhandler.py in __call__(self, attempt_number, response, caught_exception)
    231             return self._check_response(attempt_number, response)
    232         elif caught_exception is not None:
--> 233             return self._check_caught_exception(
    234                 attempt_number, caught_exception)
    235         else:

/srv/conda/envs/notebook/lib/python3.8/site-packages/botocore/retryhandler.py in _check_caught_exception(self, attempt_number, caught_exception)
    374         # the MaxAttemptsDecorator is not interested in retrying the exception
    375         # then this exception just propogates out past the retry code.
--> 376         raise caught_exception

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/endpoint.py in _do_get_response(self, request, operation_model, context)
    150             http_response = first_non_none_response(responses)
    151             if http_response is None:
--> 152                 http_response = await self._send(request)
    153         except aiohttp.ClientConnectionError as e:
    154             e.request = request  # botocore expects the request property

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/endpoint.py in _send(self, request)
    235 
    236     async def _send(self, request):
--> 237         return await self.http_session.send(request)
    238 
    239 

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiobotocore/httpsession.py in send(self, request)
    184             raise SSLError(endpoint_url=request.url, error=e)
    185         except (ClientConnectorError, socket.gaierror) as e:
--> 186             raise EndpointConnectionError(endpoint_url=request.url, error=e)
    187         except (ClientProxyConnectionError, ClientHttpProxyError) as e:
    188             raise ProxyConnectionError(proxy_url=mask_proxy_url(proxy_url), error=e)

EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.embassy.ebi.ac.uk/idr/share/community-call-2020-10-29/idr0002-heriche-condensation/plate1_1_013/422.zarr/Run%20422/E/11/Field_1/0/.zarray"

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<timed exec> in <module>

NameError: name 'data' is not defined

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-2580e56682ec> in <module>
     36             image_name = 'OrigGreen'
     37 
---> 38         inject_image_module = InjectImage(image_name, plane)
     39         inject_image_module.set_module_num(1)
     40         pipeline_copy.add_module(inject_image_module)

NameError: name 'plane' is not defined

```

</details>

**Comment by jburel** [comment]
ok. I probably need to rebase/review this old PR

**Comment by pwalczysko** [comment]
the other 3 notebooks in this repo (fruitfly, 0002 and 0002_save) worked fine.

**Comment by jburel** [comment]
you could still get it for Debian 11 for example e.g. https://apt.postgresql.org/pub/repos/apt/dists/bullseye-pgdg/9.6/
I opted to remove to avoid confusion since this is not really a version we recommend

**Comment by jburel** [comment]
replaced by #22

**Pull request closed without merging**
